// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using testV.Models;

namespace testV.Models
{
    public partial interface IVezeetaContextProcedures
    {
        Task<List<FindDoctorByIDResult>> FindDoctorByIDAsync(int? dID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<FindDoctorByNameResult>> FindDoctorByNameAsync(string doctorName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<FindDoctorBySearchResult>> FindDoctorBySearchAsync(string speciality, string governorate, string city, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllOffersResult>> GetAllOffersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetDoctorBySearchResult>> GetDoctorBySearchAsync(string speciality, string governorate, string city, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetDoctorBySpecialityAndLocationResult>> GetDoctorBySpecialityAndLocationAsync(string speciality, string governorate, string city, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetOfferByIdResult>> GetOfferByIdAsync(int? offerId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
